web:
  image: nginx:latest
  ports:
    - "9080:80"
  volumes:
    - ./code:/code
    - ./site.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
php:
  build: ./php
  # image: php:7-fpm
  volumes:
    - ./code:/code
  links:
    - postgres
  environment:
    DATABASE_URL: postgres://todoapp@postgres/todos
postgres:
  image: postgres
  environment:
    POSTGRES_USER: postgres 
    POSTGRES_PASSWORD: Developer 
    POSTGRES_DB: demodb 
  volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
